version: '3.6'

services:
    mysql:
        ports:
            - "4306:3306"

    api:
        volumes:
            - ./api:/srv/api:rw,cached
            # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
            # - ./api/var:/srv/api/var:rw

    nginx:
        volumes:
            - ./api/public:/srv/api/public:ro
        ports:
            - "8080:80"

    varnish:
        ports:
            - "8081:80"

    app:
        expose:
            - "8888"
        ports:
            - "80:3000"
            - "8888:8888"
